#ifndef CONFIG_H
#define CONFIG_H

#define EMULATOR_WINDOW_TITLE "CHIP 8"
#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_WIDTH 64
#define CHIP8_HEIGHT 32
#define CHIP_WINDOW_MULTIPLIER 10
#define CHIP_TOTAL_DATA_REGISTERS 16



#endif